### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/dos-azul-lambda#30]
Add the ability to deploy from git tags.

https://chalice.readthedocs.io/en/latest/topics/cd.html

https://github.com/DataBiosphere/dos-gdc-lambda/issues/17

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-20)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-20
┆Epic: DAL One point ohh

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

The current dev deployment needs to be removed when this is in place. [~mbaumann]

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Great work natan\! We just have some last configuration settings to adjust what instance dev points to and can close today I think\!

**Comment by natanlao** [comment]
After speaking with @david4096, I believe we can consider this issue closed.

Travis is configured to deploy every commit to `dev` and every tagged commit to `staging`. Deployment is performed with Chalice, and the requisite configuration is stored in-repo (as `.chalice/deployed/{dev,staging}.travis.json` - renamed so that an end user can deploy dos-azul-lambda themselves transparently).

Neither deployment is currently configured with a custom domain.

**Comment by natanlao** [comment]
It turns out that this issue could not be considered closed as the previous implementation resulted in API Gateway leakage. It also made it hard to configure a custom domain.

I've updated the deployment mechanism to leverage Travis's builtin Lambda deployment feature. There are some shortcomings that have been documented in-repo (see [here](.chalice/README.md)).

That said, everything seems to be up and running: http://dos.commons.ucsc-cgp-dev.org/swagger.json
