### ISSUE TITLE
Alias search returns unexpected results

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/dos-azul-lambda#35]
Likely due to the analyzer in azul making assumptions about the content of keys (especially UUIDs).

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-25)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-25

**Comment by mikebaumann** [comment]
Reposting from messages previously sent on Slack:
chael Baumann [20 hours ago]
Thanks David, please try some of the unexpected/problematic searches again, but this time append `.keyword` to the field name (e.g. `aliases.keyword`) and let me know the results. Then I can add appropriate comments to the issue above.


Michael Baumann [16 hours ago]
Hi @david4096, I did a few ES queries in Kabana, and what I suggested above is working as I expected, and I think as you expect as well. For example:
```GET /fb_index/_search
{
  "query": {
    "match": {"aliases.keyword": "dg.4503/bc4bdd84-9c6e-4321-97b5-c4c9893f096b"}
  }
}
```
the above matches one record.

```
GET /fb_index/_search
{
  "query": {
    "match": {"aliases.keyword": "dg"}
  }
}
```
the above matches no records.

```
GET /fb_index/_search
{
  "query": {
    "match": {"aliases": "dg"}
  }
}
```
the above (without the `.keyword`) matches 224 records.


Michael Baumann [15 hours ago]
I _think_ this is the default Elasticsearch behavior. In any case, a `.keyword` subfield that is not analyzed is the current behavior for both the Commons and HCA azul index.
The HCA mappings may be seen here: https://github.com/DataBiosphere/azul/blob/878426d2233992a2bc855713693d68c6fef855e6/indexer/project/hca/config.py#L25 and consist of:
```
"dynamic_templates": [
                {
                    "strings": {
                        "match_mapping_type": "string",
                        "mapping": {
                            "type": "text",
                            "analyzer": "autocomplete",
                            "search_analyzer": "standard",
                            "fields": {
                                "keyword": {
                                    "type": "keyword",
                                    "ignore_above": 256
                                }
                            }
                        }
                    }
                }
            ]
        }
```

For Commons, the current dynamic_templates mappings are as follows:
```
"dynamic_templates": [
          {
            "strings": {
              "match_mapping_type": "string",
              "mapping": {
                "analyzer": "autocomplete",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                },
                "search_analyzer": "standard",
                "type": "text"
              }
            }
          }
        ],
```

Michael Baumann [15 hours ago]
Note that for the DSS primary index (for better or worse) we changed the dynamic_template configuration so that the field name itself of is type `keyword` by default, and if you want full text search, you use the `.text` subfield instead.
